name: sampledjango

# Settings and configurations that are common for all containers
x-busybox-common: &busybox-common
  image: busybox

services:
  busybox-db:
    <<: *busybox-common
    volumes:
      - db_data:/var/lib/postgresql/data

  busybox-minio:
    <<: *busybox-common
    volumes:
      - minio_data:/data

  busybox-redis:
    <<: *busybox-common
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      target: dev-env
    command: manage.py runserver 0.0.0.0:8000 --settings config.settings.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '8000:8000'
    depends_on:
      - postgres
      - redis
      - minio
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes_from:
      - busybox-db
    depends_on:
      - busybox-db
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    restart: always

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes_from:
      - busybox-minio
    depends_on:
      - busybox-minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data

  redis:
    image: redis
    restart: always
    volumes_from:
      - busybox-redis
    depends_on:
      - busybox-redis
    ports:
      - 6379:6379

volumes:
  db_data:
  minio_data:
  redis_data: